"""
Documentation Agent

Creates reports, maintains wiki, generates documentation.
"""

import logging
import time
from typing import Any, Dict

from agents.base import BaseAgent, AgentRole, AgentMessage

logger = logging.getLogger(__name__)


class DocumentationAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            role=AgentRole.DOCUMENTATION,
            name="Documentation",
            description="Creates reports and maintains documentation",
            permissions=["read", "write", "document"],
            tools=["report_generator", "wiki_editor"],
        )

    async def process(self, message: AgentMessage) -> AgentMessage:
        content = message.content
        content_lower = content.lower()

        doc_type = "document"
        if any(kw in content_lower for kw in ["report", "summary", "assessment"]):
            doc_type = "security assessment report"
        elif any(kw in content_lower for kw in ["readme", "overview", "project"]):
            doc_type = "project overview"

        llm_doc = await self._llm_generate(
            prompt=(
                f"Generate a well-structured {doc_type} based on the following input. "
                f"Use proper markdown formatting with headers, sections, and clear structure.\n\n"
                f"Input:\n{content}"
            ),
            system_prompt=(
                "You are the Documentation agent for the ELIOT cybersecurity system. "
                "Create professional, well-structured security documentation and reports. "
                "Use markdown formatting with clear sections, bullet points, and actionable items."
            ),
            max_tokens=2048,
            temperature=0.4,
        )

        if llm_doc:
            return AgentMessage(
                sender=self.name,
                receiver=message.sender,
                content=llm_doc.strip(),
                message_type="document",
                metadata={"doc_type": doc_type, "generated_at": time.time(), "source": "llm"},
            )

        doc = self._create_document(content, message.metadata)
        return AgentMessage(
            sender=self.name,
            receiver=message.sender,
            content=doc,
            message_type="document",
            metadata={"doc_type": "report", "generated_at": time.time(), "source": "template"},
        )

    def _create_document(self, content: str, metadata: Dict[str, Any]) -> str:
        content_lower = content.lower()

        if any(kw in content_lower for kw in ["report", "summary", "assessment"]):
            return self._assessment_report(content)
        if any(kw in content_lower for kw in ["readme", "overview", "project"]):
            return self._project_overview(content)

        return self._generic_document(content)

    def _assessment_report(self, content: str) -> str:
        return (
            "# Security Assessment Report\n\n"
            f"**Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
            f"**Analyst:** ELIOT Automated System\n"
            f"**Status:** Draft\n\n"
            "---\n\n"
            "## Executive Summary\n\n"
            "[To be completed based on assessment findings]\n\n"
            "## Scope\n\n"
            "- Target: [Authorized target]\n"
            "- Methodology: [Assessment type]\n"
            "- Duration: [Time period]\n\n"
            "## Findings\n\n"
            "### Critical\n\n"
            "[None identified]\n\n"
            "### High\n\n"
            "[None identified]\n\n"
            "### Medium\n\n"
            "[None identified]\n\n"
            "### Low\n\n"
            "[None identified]\n\n"
            "## Recommendations\n\n"
            "1. [Recommendation 1]\n"
            "2. [Recommendation 2]\n\n"
            "## Methodology\n\n"
            "This assessment was conducted following authorized testing procedures.\n\n"
            "---\n\n"
            "*Generated by ELIOT - Embedded Local Intelligence Operations Terminal*\n"
        )

    def _project_overview(self, content: str) -> str:
        return (
            "# ELIOT Project Overview\n\n"
            "## What is ELIOT?\n\n"
            "ELIOT (Embedded Local Intelligence Operations Terminal) is a fully local, "
            "offline-capable AI cybersecurity companion.\n\n"
            "## Key Features\n\n"
            "- Local AI inference (no cloud required)\n"
            "- Multi-agent reasoning system\n"
            "- Voice and vision interaction\n"
            "- 3D cyberpunk avatar interface\n"
            "- Offline knowledge base\n"
            "- Authorized target whitelist\n\n"
            "## Architecture\n\n"
            "Microservice architecture running on Docker Compose:\n"
            "- Core Service (FastAPI)\n"
            "- Agent Framework\n"
            "- Knowledge Engine\n"
            "- Voice System\n"
            "- Vision System\n"
            "- Avatar Engine\n\n"
            "## Hardware\n\n"
            "- NVIDIA Jetson Orin Nano 8GB\n"
            "- NVMe storage\n"
            "- 7\" SPI TFT touchscreen\n"
            "- Camera, Microphone, Speaker\n"
        )

    def _generic_document(self, content: str) -> str:
        return (
            f"# Document\n\n"
            f"**Generated:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n"
            f"## Content\n\n"
            f"{content}\n\n"
            f"---\n\n"
            f"*Generated by ELIOT Documentation Agent*\n"
        )
